service: lunch-picker

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  prefix: LunchPicker
  stage: ${opt:stage, self:provider.stage}
  tableThroughputs:
    prod: 5
    default: 1
  tableThroughput: ${self:custom.tableThroughputs.${self:custom.stage}, self:custom.tableThroughputs.default}
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

provider:
  name: aws
  runtime: nodejs8.10
  stage: dev
  region: us-east-1

  environment:
    lunchesTable:
      Ref: LunchesTable
    locationsTable:
      Ref: LocationsTable

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - 'dynamodb:DescribeTable'
        - 'dynamodb:Query'
        - 'dynamodb:Scan'
        - 'dynamodb:GetItem'
        - 'dynamodb:PutItem'
        - 'dynamodb:UpdateItem'
        - 'dynamodb:DeleteItem'
      Resource:
        - 'Fn::GetAtt': [ LocationsTable, Arn ]
        - 'Fn::GetAtt': [ LunchesTable, Arn ]

functions:
  addLunch:
    handler: addLunch.main
    events:
      - http:
          path: '{groupName}'
          method: post
          cors: true
          authorizer: aws_iam
    environment:
  listLunches:
    handler: listLunches.main
    events:
      - http:
          path: '{groupName}'
          method: get
          cors: true
          authorizer: aws_iam
  addLocation:
    handler: addLocation.main
    events:
      - http:
          path: '{groupName}/{lunchDate}'
          method: post
          cors: true
          authorizer: aws_iam
  listLocations:
    handler: listLocations.main
    events:
      - http:
          path: '{groupName}/{lunchDate}'
          method: get
          cors: true
          authorizer: aws_iam
  getLocation:
    handler: getLocation.main
    events:
      - http:
          path: '{groupName}/{lunchDate}/{locationName}'
          method: get
          cors: true
          authorizer: aws_iam
  addVote:
    handler: addVote.main
    events:
      - http:
          path: '{groupName}/{lunchDate}/{locationName}'
          method: post
          cors: true
          authorizer: aws_iam

resources:
  - ${file(resources/dynamo.yml)}
  - ${file(resources/user-pool.yml)}
  - ${file(resources/identity-pool.yml)}
